/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import ClasesVarias.ClaseEncuesta;
import ClasesVarias.Validadores;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolo
 */
public class FormularioCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCliente
     */
    public FormularioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_NroClie = new javax.swing.JLabel();
        Txt_NroClie = new javax.swing.JTextField();
        Txt_Nombre = new javax.swing.JTextField();
        Lbl_Nombre1 = new javax.swing.JLabel();
        Txt_Apellido = new javax.swing.JTextField();
        Lbl_Apellido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Sld_Aten = new javax.swing.JSlider();
        Sld_Reco = new javax.swing.JSlider();
        Sld_Reso = new javax.swing.JSlider();
        Lbl_encAte = new javax.swing.JLabel();
        Lbl_encReso = new javax.swing.JLabel();
        Lbl_encReco = new javax.swing.JLabel();
        Lbl_Encu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Envio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Adobe Arabic", 0, 14)); // NOI18N

        Lbl_NroClie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Lbl_NroClie.setText("Nro. Cliente");
        Lbl_NroClie.setFocusable(false);

        Txt_NroClie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Txt_NroClie.setToolTipText("Ingrese un Nro. de Cliente menor a 13 cifras");

        Txt_Nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Txt_Nombre.setToolTipText("Ingrese un Nombre entre 3 y 25 caract.");
        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });

        Lbl_Nombre1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Lbl_Nombre1.setText("Nombre");
        Lbl_Nombre1.setFocusable(false);

        Txt_Apellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Txt_Apellido.setToolTipText("Ingrese un Apellido entre 2 y 20 caracteres");

        Lbl_Apellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Lbl_Apellido.setText("Apellido");
        Lbl_Apellido.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        Sld_Aten.setMajorTickSpacing(1);
        Sld_Aten.setMaximum(10);
        Sld_Aten.setMinorTickSpacing(1);
        Sld_Aten.setPaintLabels(true);
        Sld_Aten.setPaintTicks(true);
        Sld_Aten.setToolTipText("Nivel de Atencion");
        Sld_Aten.setValue(5);

        Sld_Reco.setMajorTickSpacing(1);
        Sld_Reco.setMaximum(10);
        Sld_Reco.setMinorTickSpacing(1);
        Sld_Reco.setPaintLabels(true);
        Sld_Reco.setPaintTicks(true);
        Sld_Reco.setToolTipText("Nivel de Recomendacion");
        Sld_Reco.setValue(5);

        Sld_Reso.setMajorTickSpacing(1);
        Sld_Reso.setMaximum(10);
        Sld_Reso.setMinorTickSpacing(1);
        Sld_Reso.setPaintLabels(true);
        Sld_Reso.setPaintTicks(true);
        Sld_Reso.setToolTipText("Nivel de Resolucion");
        Sld_Reso.setValue(5);

        Lbl_encAte.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_encAte.setText("Atencion:");

        Lbl_encReso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_encReso.setText("Resolucion:");

        Lbl_encReco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_encReco.setText("Recomendacion:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_encAte, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_encReso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_encReco, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sld_Aten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sld_Reco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sld_Reso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_encAte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sld_Aten, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sld_Reco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_encReco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Sld_Reso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_encReso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Lbl_Encu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Lbl_Encu.setText("Encuesta: Seleccione el Nivel de Satisfacion (0: Bajo - 10: Alto)");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Encuesta Clientes");

        Btn_Envio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Btn_Envio.setText("Enviar");
        Btn_Envio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Encu, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_Nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt_NroClie, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lbl_NroClie, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(Btn_Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Nombre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_Apellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_NroClie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt_NroClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Lbl_Encu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Btn_Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void Btn_EnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EnvioActionPerformed
        // TODO add your handling code here:
       Validadores valido = new Validadores();
       String NomClie, ApeClie="", NrClie;
       int N1, N2, N3;
       Double Prom;
       boolean ResOK;

//   Valido Nombre Cliente ............
         NomClie = valido.validarNombreApellido(Txt_Nombre.getText(),3,25);
      if( NomClie.isEmpty()){    
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Nombre de Cliente Ingresado.");     
      }else 
            ResOK=true;

//   Valido Apellido Cliente ............
      if(ResOK){
         ApeClie = valido.validarNombreApellido(Txt_Apellido.getText(),2,20);
      if( ApeClie.isEmpty()){    
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Apellido del Cliente Ingresado.");     
      }else 
            ResOK=true;
      }

//   Valido Nro. Cliente ............
      if(ResOK){
         ResOK = valido.validarNumeros(Txt_NroClie.getText(),12);
        if( !ResOK){    
            ResOK=false;
            JOptionPane.showMessageDialog(null, "Error en el Nro. de Cliente Ingresado.");     
        }
      }
      if(ResOK){
          
          N1= (int) Sld_Aten.getValue();
          N2= (int) Sld_Reco.getValue();
          N3= (int) Sld_Reso.getValue();
          NrClie=Txt_NroClie.getText().trim();
          
          ClaseEncuesta miencuesta = new ClaseEncuesta(N1,N2,N3,NomClie,ApeClie,NrClie);
          Frm_PromEncuesta frm_prome = new Frm_PromEncuesta();
          frm_prome.setDefaultCloseOperation(Frm_PromEncuesta.DO_NOTHING_ON_CLOSE);
          Prom=miencuesta.promedio(N1, N2, N3);
          frm_prome.cargodatos(NrClie, Prom);
          frm_prome.setVisible(true);
          this.dispose();
          
      }

    }//GEN-LAST:event_Btn_EnvioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Envio;
    private javax.swing.JLabel Lbl_Apellido;
    private javax.swing.JLabel Lbl_Encu;
    private javax.swing.JLabel Lbl_Nombre1;
    private javax.swing.JLabel Lbl_NroClie;
    private javax.swing.JLabel Lbl_encAte;
    private javax.swing.JLabel Lbl_encReco;
    private javax.swing.JLabel Lbl_encReso;
    private javax.swing.JSlider Sld_Aten;
    private javax.swing.JSlider Sld_Reco;
    private javax.swing.JSlider Sld_Reso;
    private javax.swing.JTextField Txt_Apellido;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_NroClie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
